### ISSUE TITLE
Issue: Beep and voice 

### ISSUE THREAD

**Issue by nicoleahmed** [timer-machine/timer-machine-android#29]
Hi
Great app Dewey

I've installed on a pixel 6 with all latest updates (5/5/23 security update)

I've tried using the app installed from f droid and play store.

Issue is that beeps don't consistently play in sections or even at the choosing the beep sound stage.

Also voice struggles with sounds over 2 syllables. Eg rest is fine but contract - is delayed and only "tract" is said.

I've got the tts voices downloaded from Google.

Thanks for the help

**Comment by nicoleahmed** [comment]
I think it's something to do with connecting to bluetooth sound devices.

**Comment by DeweyReed** [comment]
By "don't consistently play in sections," do you mean the time before it plays varies, or the sound doesn't sound as expected? Are you referring to beep or voice(Text-to-speech)?

The beep is from the system, and I haven't found a way to adjust it too much other than playing or stopping it.

**Comment by DeweyReed** [comment]
Is the problem only happening when using Bluetooth audio devices? If so, there is nothing the app can do to improve the situation. The app plays any sound, and the system decides to play through a speaker or Bluetooth.

Text-to-speech takes some time to process. It could cause some delays because of a poor internet connection.

**Comment by nicoleahmed** [comment]
Thank I think so.,so I'll close this issue. Many thanka
