### ISSUE TITLE
Confusion between "normal" and "notifier" steps in TimeR Machine

### ISSUE THREAD

**Issue by mathe00** [timer-machine/timer-machine-android#81]
Hello,

I would like to address a confusion I've noticed in the TimeR Machine application. I've observed that there are two types of steps in the application: "normal" steps and "notifier" steps. However, apart from the color of the step tile, I don't see a clear distinction between these two types of steps.

Indeed, upon examining the functionalities available for each type of step, I find that it's possible to perform the same actions or trigger the same events, such as playing music, vibrations, beeps, notifications, etc., for both "normal" steps and "notifier" steps.

This similarity leads me to wonder if there's a real difference in functionality or usage between these two types of steps, or if the only distinction lies in the color of the step tile.

I would like to understand this distinction to make the best use of TimeR Machine's features. If possible, could you clarify this point for me?

I also want to apologize if this question is already addressed somewhere in the application's documentation. I'm still exploring the application, and I may have missed this information.

Thank you very much for your attention and for the work you've put into developing TimeR Machine.

**Comment by DeweyReed** [comment]
Thanks for using the app! :D

In short, apart from the different colors, an option in the app settings called "When plus time at a notifier" targets only notifiers. And that's it.

The existence of the notifier is more of a historical reason. The app was initially developed as a successor of a similar but simpler app that can only run steps and insert reminders like music and vibration between every two steps. Therefore, this app introduced the notifier to separate normal steps. To this day, it only offers a little, and even the option in the app settings feels somewhat redundant to me.

Because everything works fine right now, and the amount of legacy code is vast, I don't plan to change it. If there is anything that can be improved, feel free to tell me. Although I have little time to maintain, I'll try my best to squeeze in some time.

**Comment by mathe00** [comment]
> Thanks for using the app! :D
> 
> In short, apart from the different colors, an option in the app settings called "When plus time at a notifier" targets only notifiers. And that's it.
> 
> The existence of the notifier is more of a historical reason. The app was initially developed as a successor of a similar but simpler app that can only run steps and insert reminders like music and vibration between every two steps. Therefore, this app introduced the notifier to separate normal steps. To this day, it only offers a little, and even the option in the app settings feels somewhat redundant to me.
> 
> Because everything works fine right now, and the amount of legacy code is vast, I don't plan to change it. If there is anything that can be improved, feel free to tell me. Although I have little time to maintain, I'll try my best to squeeze in some time.

Thank you for your answer, I understand clearly now.
